version: "3.8"

services:
  mongo-to-language:
    container_name: mongo-to-language
    image: mongo:${MONGO_VERSION}
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./.docker-volumes/mongo:/data/db
      - ./mongo:/data/configdb
    ports:
      - ${MONGO_PORT}:27017
    networks:
      to-language-net:
        ipv4_address: 172.28.1.1

  application-to-language:
    container_name: application-to-language
    build: ./
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mongo-to-language
    ports:
      - ${APP_PORT}:8080
    networks:
      to-language-net:
        ipv4_address: 172.28.1.2

networks:
  to-language-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16