debug: ${SPRING_DEBUG:false}
server:
  port: ${APP_PORT:8080}
  forward-headers-strategy: framework
spring:
  application:
    name: to-language
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      database: ${MONGO_INITDB_DATABASE}

application:
  url: ${APP_URL}
  api-path: ${API_PATH:/}
  hash-salt: ${HASH_SALT}
  jwt-signing-key: ${JWT_SIGNING_KEY}
  access-token-ttl: ${TOKEN_TTL:30m}
  refresh-token-ttl: ${TOKEN_TTL:30m}
  session:
    max: ${SESSION_MAX:3}
  cache:
    user-maximum-size: 1000
    user-expired-time: 1h

mail:
  service:
    host: localhost
    port: 8088